
---
title: "Modellazione statistica e grafica su GSS"
author: "Riccardo Fantechi"
date: " \\textit{Università degli Studi di Firenze} "
output: 
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
    includes:
      in_header: main.tex
fontsize: 11pt
geometry: margin=2.5cm
---


\begin{center}
\hrulefill
\end{center}

\vspace{0.8em}

\begin{abstract}
In questa analisi statistica esploriamo le opinioni degli intervistati del dataset GSS riguardo la regolamentazione delle armi da fuoco. L’obiettivo principale è costruire e confrontare modelli grafici e predittivi, al fine di comprendere quali fattori sociodemografici influenzano il supporto a leggi restrittive come GUNLAW.
\end{abstract}

\begin{multicols}{2}

# Introduzione

In questa analisi andremo a studiare il comportamento della variabile 

# Pulizia e Preprocessing del dataset

## Caricamento del dataset

## Rimozione dei valori mancanti

## Codifica delle variabili in fattori

# Analisi esplorativa

## Statistiche descrittive

## Tabelle di contingenza e percentuali

## Visualizzazione grafica con Heatmap e Barplot

# Modelli grafici indiretti

## Introduzione ai modelli log-lineari

## Costruzione del modello 

## Interpretazione delle dipendenze

# Modelli grafici diretti (Reti Bayesiane)

## Introduzione alle Reti Bayesiane

## Algoritmo Hill climbing

## Interpretazione

# Regressione Logistica per Confronto

## Specificazione del modello

## Analisi dei coefficienti

## Interpretazione dei risultati

# Selezione del Modello (AIC e BIC)

## Confronto tra modelli grafici

## Confronto tra reti bayesiane

## Confronto con regressione logistica

# Conclusioni e Interpretazioni Finali

## Sintesi dei risultati

## Limiti dell’analisi

## Spunti per analisi future

\end{multicols}








